# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-11-23 06:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('ae', models.BigIntegerField(blank=True, null=True)),
                ('cp', models.BigIntegerField(blank=True, null=True)),
                ('bf_bip', models.CharField(choices=[('BF', 'Budget de Fonctionement'), ('BIP', "Budget d'Investissement")], max_length=3)),
                ('status', models.CharField(choices=[('LF', 'Loi de Finance'), ('REV', 'Revised'), ('EX', 'Executed')], max_length=3)),
                ('region', models.CharField(choices=[('EN', 'Extrême-Nord'), ('NO', 'Nord'), ('AD', 'Adamaoua'), ('LT', 'Littoral'), ('CE', 'Centre'), ('OU', 'Ouest'), ('NW', 'North-West'), ('SW', 'South-West'), ('SU', 'Sud'), ('ES', 'Est'), ('AC', 'Administration Centrale')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('pg_id', models.CharField(blank=True, max_length=20, null=True)),
                ('exercice_id', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(max_length=10)),
                ('ae', models.BigIntegerField(blank=True, null=True)),
                ('cp', models.BigIntegerField(blank=True, null=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('objective_fr', models.TextField(blank=True, null=True)),
                ('objective_en', models.TextField(blank=True, null=True)),
                ('indicator_fr', models.TextField(blank=True, null=True)),
                ('indicator_en', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(blank=True, null=True)),
                ('short_name', models.CharField(max_length=20)),
                ('full_name_fr', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name_en', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='budgetprogramme',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Chapitre'),
        ),
        migrations.AddField(
            model_name='annualentry',
            name='chapitre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Chapitre'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetprogramme',
            unique_together=set([('year', 'chapitre', 'code')]),
        ),
        migrations.AlterUniqueTogether(
            name='annualentry',
            unique_together=set([('year', 'chapitre', 'status', 'region', 'bf_bip')]),
        ),
    ]
