# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-11-23 06:17
from __future__ import unicode_literals

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArmpContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niu_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.NullBooleanField()),
                ('from_registration', models.SmallIntegerField(blank=True, null=True)),
                ('is_contribuables_scanned', models.BooleanField(default=False)),
                ('maitre_ouvrage', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=2550)),
                ('date', models.DateField(blank=True, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('titulaire', models.CharField(blank=True, max_length=255)),
                ('status', models.IntegerField(choices=[(1, 'INFRUCTUEUX'), (2, 'ANNULE'), (3, 'ATTRIBUE'), (4, 'SIGNE'), (5, 'RESILIE'), (6, 'RECEPTIONNE')])),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('s_unique', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ArmpEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('link', models.URLField(verbose_name='primary source')),
                ('publication_type', models.CharField(blank=True, max_length=20, null=True)),
                ('verbose_type', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_datetime', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('expiration_time', models.TimeField(blank=True, null=True)),
                ('dao_link', models.URLField(blank=True, verbose_name='DAO link')),
                ('original_link', models.URLField(blank=True, verbose_name='Original Document link')),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('extra_content', models.TextField(blank=True, null=True)),
                ('projected_cost', models.BigIntegerField(blank=True, null=True)),
                ('final_cost', models.BigIntegerField(blank=True, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('ao_id', models.CharField(blank=True, max_length=50, null=True)),
                ('own_id', models.CharField(blank=True, max_length=50, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CDI_CRI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cri', models.CharField(max_length=50, verbose_name='Centre Régional des Impôts')),
                ('cdi', models.CharField(max_length=50, verbose_name='Centre des Impôts de Rattachement')),
                ('matches', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'CDIs',
            },
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niu', models.CharField(max_length=50, unique=True)),
                ('raison_sociale', models.CharField(blank=True, max_length=255, null=True)),
                ('sigle', models.CharField(blank=True, max_length=255, null=True)),
                ('activite_principale', models.CharField(blank=True, max_length=255, null=True, verbose_name='Activité Principale')),
                ('bp', models.PositiveIntegerField(blank=True, null=True, verbose_name='Boite Postale')),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('etat_niu', models.CharField(blank=True, max_length=20, null=True)),
                ('forme_juridique', models.CharField(blank=True, max_length=50, null=True)),
                ('lieu_dit', models.CharField(blank=True, max_length=50, null=True)),
                ('regime', models.CharField(blank=True, choices=[('IL', 'IMPOT LIBERATOIRE'), ('REEL', 'REGIME REEL'), ('RSI', 'REGIME SIMPLIFIE'), ('HRI', "HORS REGIME D'IMPOSITION"), ('SAL', 'SALARIE')], max_length=4, null=True)),
                ('regime_sub', models.CharField(blank=True, choices=[('PP', 'Personne Physique'), ('PM', 'Personne Morale'), ('A', 'A'), ('A2', 'A2'), ('A3', 'A3'), ('B', 'B'), ('B2', 'B2'), ('B3', 'B3'), ('C', 'C'), ('C', 'C2'), ('D', 'D')], max_length=2, null=True)),
                ('region', models.CharField(blank=True, max_length=25, null=True, verbose_name='Région Administrative')),
                ('departement', models.CharField(blank=True, max_length=50, null=True)),
                ('ville', models.CharField(blank=True, max_length=50, null=True)),
                ('commune', models.CharField(blank=True, max_length=50, null=True)),
                ('quartier', models.CharField(blank=True, max_length=255, null=True)),
                ('vente_boisson', models.CharField(blank=True, max_length=20, null=True)),
                ('id_classe_activite', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['sigle', 'raison_sociale'],
            },
        ),
        migrations.CreateModel(
            name='EntrepriseChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niu', models.CharField(max_length=255)),
                ('log', models.CharField(max_length=255)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-exercice__year', '-exercice__month'],
            },
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.IntegerField(choices=[(1, 'JANVIER'), (2, 'FEVRIER'), (3, 'MARS'), (4, 'AVRIL'), (5, 'MAI'), (6, 'JUIN'), (7, 'JUILLET'), (8, 'AOUT'), (9, 'SEPTEMBRE'), (10, 'OCTOBRE'), (11, 'NOVEMBRE'), (12, 'DECEMBRE')])),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='TenderOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['owner_id'],
            },
        ),
        migrations.CreateModel(
            name='WBContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niu_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.NullBooleanField()),
                ('from_registration', models.SmallIntegerField(blank=True, null=True)),
                ('is_contribuables_scanned', models.BooleanField(default=False)),
                ('contract_id', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('cost', models.BigIntegerField()),
                ('team_fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('procurement_group', models.CharField(blank=True, max_length=255, null=True)),
                ('procurement_group_description', models.CharField(blank=True, max_length=255, null=True)),
                ('procurement_meth_text', models.CharField(blank=True, max_length=255, null=True)),
                ('rw_type', models.CharField(blank=True, max_length=255, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date', 'project__project_id'],
            },
        ),
        migrations.CreateModel(
            name='WBProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=20, unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('link', models.URLField(verbose_name='primary source')),
                ('financial_type', models.CharField(blank=True, max_length=10, null=True)),
                ('main_theme', models.CharField(blank=True, max_length=255, null=True)),
                ('main_sector', models.CharField(blank=True, max_length=255, null=True)),
                ('is_scanned', models.BooleanField(default=False)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Closed'), (1, 'Active'), (2, 'Dropped'), (3, 'Pipeline')], null=True)),
                ('agency', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('cost', models.BigIntegerField(blank=True, null=True)),
                ('lendinginstr', models.CharField(blank=True, max_length=255, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-start_date', '-cost'],
            },
        ),
        migrations.CreateModel(
            name='WBSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-supplier_id'],
            },
        ),
        migrations.AddIndex(
            model_name='wbsupplier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tender_wbsu_search__ba4277_gin'),
        ),
        migrations.AddIndex(
            model_name='wbproject',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tender_wbpr_search__406c74_gin'),
        ),
        migrations.AddField(
            model_name='wbcontract',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.WBProject'),
        ),
        migrations.AddField(
            model_name='wbcontract',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='tender.WBSupplier'),
        ),
        migrations.AlterUniqueTogether(
            name='exercice',
            unique_together=set([('year', 'month')]),
        ),
        migrations.AddField(
            model_name='entreprisechange',
            name='exercice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tender.Exercice'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='cdi_cri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tender.CDI_CRI'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='change_list',
            field=models.ManyToManyField(blank=True, to='tender.EntrepriseChange'),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='exercice_list',
            field=models.ManyToManyField(blank=True, to='tender.Exercice'),
        ),
        migrations.AlterUniqueTogether(
            name='cdi_cri',
            unique_together=set([('cdi', 'cri')]),
        ),
        migrations.AddField(
            model_name='armpentry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tender.TenderOwner'),
        ),
        migrations.AddIndex(
            model_name='armpcontract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tender_armp_search__ce5ae8_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='armpcontract',
            unique_together=set([('s_unique',), ('maitre_ouvrage', 'title', 'year', 'titulaire', 'cost')]),
        ),
        migrations.AddIndex(
            model_name='wbcontract',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tender_wbco_search__c44cea_gin'),
        ),
        migrations.AddIndex(
            model_name='entreprisechange',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tender_entr_search__664634_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='entreprisechange',
            unique_together=set([('log', 'exercice', 'niu')]),
        ),
        migrations.AddIndex(
            model_name='armpentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='tender_armp_search__14306d_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='armpentry',
            unique_together=set([('owner', 'link', 'publication_type', 'verbose_type')]),
        ),
    ]
