# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2024-11-23 06:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incarceration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('name_mispelling', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'M'), (1, 'F')], null=True)),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Preferred source of image')),
                ('featured_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
                ('arrest_date', models.DateField(blank=True, null=True)),
                ('incarceration_date', models.DateField(blank=True, null=True)),
                ('conviction_date', models.DateField(blank=True, null=True)),
                ('conviction_duration_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conviction_duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('conviction_duration_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estimated_release_date', models.DateField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('deceased', models.NullBooleanField()),
                ('dates_inaccurate', models.NullBooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IncarcerationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('name_fr', models.CharField(max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('name_mispelling', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('sex', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'M'), (1, 'F')], null=True)),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Preferred source of image')),
                ('featured_image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Featured Image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=30, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='incarceration',
            name='judges',
            field=models.ManyToManyField(blank=True, null=True, to='jailed.Judge'),
        ),
        migrations.AddField(
            model_name='incarceration',
            name='prison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jailed.Prison'),
        ),
        migrations.AddField(
            model_name='incarceration',
            name='tags',
            field=models.ManyToManyField(blank=True, to='jailed.IncarcerationTag'),
        ),
    ]
